class BusinessError {
    public TOKEN_NOT_FOUND = "TOKEN_NOT_FOUND";
    public REFRESH_TOKEN_NOT_FOUND = "REFRESH_TOKEN_NOT_FOUND";
    public REGISTER_USER = "REGISTER_USER";
    public GENERIC = "GENERIC";
    public SAVED_TOKEN = "SAVED_TOKEN";
    public CONTRACT_NOT_FOUND = "CONTRACT_NOT_FOUND"
    public CONTACT_NOT_FOUND = "CONTACT_NOT_FOUND"
    public PARTNER_NOT_FOUND = "PARTNER_NOT_FOUND"
    public MODALITY_NOT_FOUND = "MODALITY_NOT_FOUND"
    public UNPROCESSABLE_ENTITY = "UNPROCESSABLE_ENTITY"
    public EMAIL_NOT_FOUND = "EMAIL_NOT_FOUND"
    public EMAIL_EXISTS = "EMAIL_EXISTS"
    public CONTACT_NOT_CREATED = "CONTACT_NOT_CREATED"
}

export default new BusinessError()
