apiVersion: v1
kind: Service
metadata:
  name: partners-db
  namespace: partners
  labels:
    app: partners-db
spec:
  ports:
    - port: 3306
  selector:
    app: partners-db
    tier: mysql
  type: ClusterIP
