apiVersion: v1
kind: Service
metadata:
  name: partners-ms
  namespace: sport-club
spec:
  selector:
    app: partners-ms
  type: NodePort
  ports:
    - name: partners-ms
      protocol: TCP
      port: 3001
      targetPort: 3001
      nodePort: 30010
